# PostgreSQL. Versions 8.2 and up are supported.

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: signup_project_development
  pool: 5
  username: signup_project
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: signup_project_test
  pool: 5
  username: signup_project
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: signup_project_production
  pool: 5
  username: signup_project
  password: 
  # password: <%= ENV['SIGNUP_PROJECT_DATABASE_PASSWORD'] %>
